simulation: {name: hybrid_adv_L100_0001_Re2000, nx: 4224, ny: 1280, nu: 0.0025, characteristic_length: 100.0,
  compute_step_size: 80, max_steps: 1000000, warmup_steps: 2000, smagorinsky_constant: 0.2,
  ghost_moments_s: 1.05}
outputs:
  enable_profiling: false
  gui: {enable: true, interval_steps: 80, max_size: 1024, show_zone_overlay: true,
    gaussian_sigma: 1.0}
  video: {enable: true, interval_steps: 80, fps: 30, filename: video_hybrid_adv_L100_0001_Re2000.mp4}
  dataset: {enable: true, interval_steps: 80, folder: output/Hyper/, compression: lzf,
    save_resolution: 512}
boundary_condition:
  type: [0, 2, 1, 2]
  value:
  - [0.05, 0.0]
  - [0.0, 0.0]
  - [0.0, 0.0]
  - [0.0, 0.0]
mask: {enable: true, type: png, invert: false, path: src/generators/hybrid_maps\hybrid_adv_L100_0001.png}
domain_zones: {sponge_y: 64, sponge_x: 128, buffer: 192, inlet_buffer: 128}
