simulation: {name: Re5000_hybrid_urban, nx: 4096, ny: 1024, nu: 0.0016, characteristic_length: 160.0,
  compute_step_size: 100, max_steps: 200000, warmup_steps: 2000, smagorinsky_constant: 0.2,
  ghost_moments_s: 1.05}
outputs:
  enable_profiling: false
  gui: {enable: false, interval_steps: 100, max_size: 1024, show_zone_overlay: true,
    gaussian_sigma: 1.0}
  video: {enable: false, interval_steps: 500, fps: 30, filename: video_Re5000.mp4}
  dataset: {enable: true, interval_steps: 100, folder: output/Hyper/Re5000_data/,
    compression: lzf, save_resolution: 512}
boundary_condition:
  type: [0, 2, 1, 2]
  value:
  - [0.05, 0.0]
  - [0.0, 0.0]
  - [0.0, 0.0]
  - [0.0, 0.0]
mask: {enable: true, type: png, invert: false, path: src/GenMask/generated_maps_advanced/hybrid_adv_0000.png}
domain_zones: {sponge_y: 64, sponge_x: 128, buffer: 64, inlet_buffer: 128}
