simulation: {nx: 4096, ny: 1024, max_steps: 1000000, warmup_steps: 2000, smagorinsky_constant: 0.2,
  ghost_moments_s: 1.2, name: Case04_Re1000_L100.png, nu: 0.005, characteristic_length: 100.0,
  compute_step_size: 80}
outputs:
  enable_profiling: false
  gui: {enable: true, max_size: 1024, show_zone_overlay: true, gaussian_sigma: 1.0,
    interval_steps: 80}
  video: {enable: true, fps: 30, interval_steps: 80, filename: Case04_Re1000_L100.png.mp4}
  dataset: {enable: true, compression: lzf, save_resolution: 512, interval_steps: 80}
  project_name: Hyper-1
  data_save_root: outputs\Hyper-1
  target_re: 1000
boundary_condition:
  type: [0, 2, 1, 2]
  value:
  - [0.05, 0.0]
  - &id001 [0.0, 0.0]
  - *id001
  - *id001
mask: {enable: true, type: png, invert: false, path: SimCases\Hyper-1\masks\Case04_Re1000_L100.png}
domain_zones: {sponge_y: 64, sponge_x: 128, buffer: 64, inlet_buffer: 128}
