simulation: {nx: 4096, ny: 1024, max_steps: 3000, warmup_steps: 200, ghost_moments_s: 1.2,
  name: L204_0007, nu: 0.00255, characteristic_length: 204.0, compute_step_size: 163,
  smagorinsky_constant: 0.2}
outputs:
  enable_profiling: false
  gui: {enable: true, max_size: 1024, show_zone_overlay: true, gaussian_sigma: 1.0,
    interval_steps: 163}
  video: {enable: true, fps: 30, interval_steps: 163, filename: L204_0007.mp4}
  dataset: {enable: true, compression: lzf, save_resolution: 512, interval_steps: 163}
  project_name: Hyper-1
  data_save_root: outputs\Hyper-1
  target_re: 4000
boundary_condition:
  type: [0, 2, 1, 2]
  value:
  - [0.05, 0.0]
  - &id001 [0.0, 0.0]
  - *id001
  - *id001
mask: {enable: true, type: png, invert: false, path: SimCases\Hyper-1\masks\L204_0007.png}
domain_zones: {sponge_y: 64, sponge_x: 128, buffer: 64, inlet_buffer: 128}
physical_constants: {kinematic_viscosity_air_m2_s: 1.5e-05, inlet_velocity_ms: 5.0}
