# config_re2000.yaml
simulation:
  name: "Production_Re2000_Square"
  nx: 800
  ny: 300

  # --- 物理參數 ---
  # Re = (0.05 * 40) / nu = 2000
  # => nu = 2.0 / 2000 = 0.001
  nu: 0.001

  # --- LES 參數 ---
  # 開始需要渦黏性模型吃掉高頻噪聲
  smagorinsky_constant: 0.25

  # --- MRT 參數 ---
  # 增強穩定性
  ghost_moments_s: 1.2

  # --- 視覺化 ---
  steps_per_frame: 100
  visualization_gaussian_sigma: 1.0 # 稍微模糊化，模擬流體質感
  warmup_steps: 2000 # 跳過初始震盪

boundary_condition:
  type: [0, 2, 1, 2] # 左(In), 上(Free-slip), 右(Out), 下(Free-slip)
  value:
    - [0.05, 0.0] # 保持 0.05，不要隨意變動速度，改變黏滯係數就好
    - [0.0, 0.0]
    - [0.0, 0.0]
    - [0.0, 0.0]
  CL: 40.0

mask:
  enable: true
  type: "rect"
  params:
    cx: 150.0
    cy: 150.0
    r: 20.0 # 總寬度 40

foler_paths:
  output: "output/re2000/"
display:
  max_size: 960
