boundary_condition:
  type:
    - 0
    - 0
    - 1
    - 0
  value:
    - - 0.05
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
display:
  max_size: 960
  zone:
    buffer: 300
    inlet_buffer: 200
    sponge_x: 400
    sponge_y: 80
foler_paths:
  output: output/DFGBenchmark2D-1/
mask:
  enable: true
  params:
    cx: 300.0
    cy: 280.0
    r: 73.0
  type: cylinder
simulation:
  characteristic_length: 146.0
  ghost_moments_s: 1.0
  name: DFG_Benchmark_Re100
  nu: 0.004866666666666666
  nx: 2400
  ny: 600
  smagorinsky_constant: 0.0
