# config_re100.yaml
simulation:
  name: "Validation_Re100_Square"
  nx: 800
  ny: 300

  # --- 物理參數 ---
  # Re = (0.05 * 40) / niu = 100
  # => niu = 2.0 / 100 = 0.02
  niu: 0.02

  # --- LES 參數 ---
  # 層流不需要 LES，但為了保持代碼一致性，設一個極小值或保持預設
  smagorinsky_constant: 0.1

  # --- MRT 參數 ---
  # 黏滯性高時，鬆弛時間長，非常穩定，s 可以設低一點
  ghost_moments_s: 1.0

  # --- 視覺化 ---
  steps_per_frame: 50 # 跑慢一點方便觀察
  visualization_gaussian_sigma: 0.0 # 驗證時不要模糊，要看清楚網格細節
  warmup_steps: 0 # 驗證時從頭看，觀察流場建立過程

boundary_condition:
  type: [0, 2, 1, 2] # 左(In), 上(Free-slip), 右(Out), 下(Free-slip)
  value:
    - [0.05, 0.0] # 入口速度降低至 0.05 以確保數值精確
    - [0.0, 0.0]
    - [0.0, 0.0]
    - [0.0, 0.0]
  CL: 40.0 # 特徵長度

mask:
  enable: true
  type: "rect"
  params:
    cx: 150.0 # 離入口稍微遠一點 (約 3~4倍直徑)
    cy: 150.0 # 置中
    r: 20.0 # 半徑/半寬 = 20 (總寬度 = 40)

foler_paths:
  output: "src/lbm_mrt_les/output/re100/"
display:
  max_size: 960
